edition = "2024"
format_code_in_doc_comments = true
format_macro_matchers = true
max_width = 120
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
use_field_init_shorthand = true
