[package]
name = "api"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
async-nats.workspace = true
axum = { version = "0.8", features = ["macros"] }
blake3 = "1"
futures-util = "0.3"
http.workspace = true
prtl-messages.workspace = true
redis = { version = "1.0.0-rc.4", features = ["tokio-comp", "connection-manager"] }
rmp-serde.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url = "2.5"
